console.log(a == a);
console.log(b == b);
console.log(a != a);

console.log(5 === 5); 
console.log(5 === "5"); 
console.log(true === 1); 

console.log(5 != 3); 
console.log(5 != "5"); 
console.log(true != 0);

console.log(5 !== 3);
console.log(5 !== "5");
console.log(true !== 0);

console.log(5 > 3);
console.log(5 > 7);

console.log(5 < 3);
console.log(5 < 7);

console.log(5 >= 3);
console.log(5 >= 7);
console.log(5 >= 5);

console.log(5 <= 3);
console.log(5 <= 7);
console.log(5 <= 5);